### ISSUE TITLE
problem when downloading the 'audioset_data'

### ISSUE THREAD

**Issue by LittleFlyingSheep** [DCASE-REPO/DESED_task#14]
When I run 'generate_dcase_task4_2021.py --basedir='../../data'', it paused as shown as follows:
![image](https://user-images.githubusercontent.com/38974045/116958303-b8e12200-accc-11eb-8d64-533d64d52797.png)
How can I make the downloading successfully?

**Comment by turpaultn** [comment]
🤔 Good question.
If it is blocked here, it could be an internet connection.
Did you try to remove the "tmp/" folder, sometimes it can cause problems ?
Then,  line 722 you could try and change: 
`desed.download_audioset_data(desed_real_folder, n_jobs=3, chunk_size=10)`
by 
`desed.download_audioset_data(desed_real_folder, n_jobs=1, chunk_size=10)` and see if this works (could be a multiprocessing problem in that case).
Let us know if something worked.

**Comment by LittleFlyingSheep** [comment]
Thanks for your help!
With experiments, 'tmp/' folder and the multiprocessing work are not the reason of this problem.  The reason is the internet connection. I have tested to download with a VPN. However, it is interesting that the work still failed in my ubuntu system but successfully in my windows one. Maybe it is an agency problem when the project calling in a ubuntu system?

**Comment by turpaultn** [comment]
This is weird indeed, I honestly have no idea where it can come from 🤔 Maybe firewall or anything like that, I don't even know if this could be from youtube_dl which would be different on your different systems...

**Comment by turpaultn** [comment]
Closing this issue since it works on one system, if someone has the same problem, feel free to reopen.
