### ISSUE TITLE
Baseline performance

### ISSUE THREAD

**Issue by SaoYear** [DCASE-REPO/DESED_task#15]
Hi, I downloaded the checkpoint from the given site.

And when I ran `train_sed.py`, the evaluation results were far less than the provided value. 
```
DATALOADER:0 TEST RESULTS
{'hp_metric': 0.4607104032219199,
 'test/student/event_f1_macro': 0.36400517676011424,
 'test/student/intersection_f1_macro': 0.6944254152896272,
 'test/student/loss_strong': 0.13684727251529694,
 'test/student/psds_score_scenario1': 0.28276984860907106,
 'test/student/psds_score_scenario2': 0.4607104032219199,
 'test/teacher/event_f1_macro': 0.3735340054530239,
 'test/teacher/intersection_f1_macro': 0.7144140221660716,
 'test/teacher/loss_strong': 0.12656442821025848,
 'test/teacher/psds_score_scenario1': 0.2917064844285735,
 'test/teacher/psds_score_scenario2': 0.47517726567916774}
```

I am wondering if my test set is correct. Could you please tell me which folder shall I check?

Many thanks

**Comment by turpaultn** [comment]
Indeed, we don't have the same results.
Could you send a mail to @RonFrancesca please, she could probably send you the test set so you can check if this is the problem.

**Comment by SaoYear** [comment]
> Indeed, we don't have the same results.
> Could you send a mail to @RonFrancesca please, she could probably send you the test set so you can check if this is the problem.

Thanks a lot, I have contacted her and found out there do exist problems with my dataset. 

Sorry I did not close this issue earlier.
