### ISSUE TITLE
Problem with Pytorch Lightning version

### ISSUE THREAD

**Issue by ferugit** [DCASE-REPO/DESED_task#22]
Newer Pytorch Lightning versions,  which are installed automatically, don't support:

```python
self.hparams = hparams
```
So, it must be used something like the following line:

```python
self.hparams.update(hparams)
```
As indicated [here](https://discuss.pytorch.org/t/pytorch-lightning-module-cant-set-attribute-error/121125). It will be nice to set in the requirements.txt the exact version to get all working (e.g. pytorch-lightning==1.2.10)

**Comment by turpaultn** [comment]
Thanks for noticing it and telling it here ! 
If you want to make a pull request, fine by me, otherwise I'll probably do it in the next days.

**Comment by turpaultn** [comment]
Solved in #23
