### ISSUE TITLE
Errors when testing with psds_eval>=0.4.0

### ISSUE THREAD

**Issue by 1yunlong** [DCASE-REPO/DESED_task#43]
It worked well when training with psds_eval>=0.4.0,But an error occurs  in the final test.
![捕获](https://user-images.githubusercontent.com/89202560/164215108-413765b2-521f-4285-9e16-656ef7dc32b4.PNG)
When I downgraded PSD_eval to 0.3.0, it worked fine. However, the published baseline cannot be reproduced, and psDS1 is 0.3153 and PSDS2 is 0.5101 using PSDS_eval ==0.3.0

**Comment by RonFrancesca** [comment]
HI @1yunlong, 

could you please point me to the validation.tsv file you are using?
Thanks.

**Comment by 1yunlong** [comment]
I used the 1168 validation set, and the validation. tsv file is 217K in size.
![捕获2](https://user-images.githubusercontent.com/89202560/164677016-685fedc0-a541-4c9c-a668-7f76f38f1dac.PNG)

**Comment by kimsojeong1225** [comment]
same issue

**Comment by RonFrancesca** [comment]
ok, 
as far as I understand, you validaton.tsv file has 4252 lines, right?

**Comment by kimsojeong1225** [comment]
> 

I followed your mentions, but didn't solve this error

**Comment by RonFrancesca** [comment]
@kimsojeong1225 
could you please share the file with me, so I can check it out?
Maybe on slack?

Thanks you!

**Comment by kimsojeong1225** [comment]
@RonFrancesca 
I sent my file to slack! 
Thanks

**Comment by 1yunlong** [comment]
Thank you for all your assistance.
