### ISSUE TITLE
Confused about the development dataset

### ISSUE THREAD

**Issue by Ming-er** [DCASE-REPO/DESED_task#49]
Sorry to bother you, but there is something really confusing us. On the task description web page, we notice that the strong labelled part of the development set only contains 10k synthetic data. However, in this repository, we find that there is some other strong labeled data (namely strong_real) that can be used to train the baseline model. So, could participants use these strong_real data to train their own model?

**Comment by SangwonSUH** [comment]
Sorry to bother you again, but I have a question with the dev set too.
There are two validation sets, `validation/validation` and `validation/synthetic21_validation` in this repository.
- Are they identical to the `public evaluation` and `synthetic evaluation` sets mentioned in the rule for not used in training/tuning?
- Or just treated as the external sets for training?

Thank you :)

**Comment by turpaultn** [comment]
Did you get the answer to your question @Ming-er ?
