### ISSUE TITLE
Is there any way to check if there's any file still missing in the dataset

### ISSUE THREAD

**Issue by waaaaangchangwen** [DCASE-REPO/DESED_task#52]
Recently I've noticed that the number of files I downloaded did not match the number in the description of  DESED dataset
most of them are weakly labeled training data, and maybe some label tsv files
(I've already downloaded the missing files provided by Ms. Ronchini)
I'm wondering if there's a list of the file names or anything else that can help me check if I'm still missing anything in my folder
Thanks

**Comment by RonFrancesca** [comment]
You can check the full list of filename from the metadata files.
