### ISSUE TITLE
Problems on pretrained model

### ISSUE THREAD

**Issue by kimsojeong1225** [DCASE-REPO/DESED_task#54]
Two problems were encountered in training and testing with pre-trained models (AST).
1. Error occurs when reading the devtest.hdf5
**[Error message]**
![Screenshot from 2022-05-30 22-08-01](https://user-images.githubusercontent.com/56779949/170999545-d96fbfd3-e3af-4f57-9db8-d38702db862d.png)
**[Error occurred point]**
![Screenshot from 2022-05-30 22-09-06](https://user-images.githubusercontent.com/56779949/170999575-83403660-9227-4ee0-94f2-763a66a59643.png)

2. The weight of the Base CRNN model and Pretrained_model are different (weights file name: epoch=156-step=18525.ckpt)
**[Error message]**
![Screenshot from 2022-05-30 22-15-12](https://user-images.githubusercontent.com/56779949/171000011-2caa9d4a-235d-49a7-952e-e419cfa54e16.png)

**Comment by popcornell** [comment]
1. Have you downloaded the data and set the paths accrodingly ? 
2. Are you trying to use the pretrained CRNN with the embedding recipe ?

**Comment by kimsojeong1225** [comment]
1. Both are done. Error while reading file.
   Attach a pic that printed k,v in devtest.hdf5. 
![Screenshot from 2022-05-31 10-06-03](https://user-images.githubusercontent.com/56779949/171073817-5f5d9127-3c3e-4b19-a8a8-c6cf74bf8806.png)
2. Yes, I used pretrained_train.py file.

**Comment by popcornell** [comment]
Maybe the h5py data is corrupted in some way ? Could it be ? 
Can you try to redownload it ? 

Regarding second issue you can't trivially use the pretrained checkpoint for the CRNN because the CRNN baseline with embeddings has additional layers as it perform late fusion with the pretrained audioset embeddings. You need to modify the code manually and load with strict=False if you want to use the pretrained CRNN and start from that one.

**Comment by kimsojeong1225** [comment]
1. I retry but occur same error
2. I think pretrained_model file that uploaded link(https://zenodo.org/record/6447197#.YpYUzUMzZNw) is not pretrained_model.
   PSDS1,2 on Readme are 32.24%, 72.22% but this link's psds1,2 are 0.35,0.55. This is same score with Baseline model(trained with strong real data)

**Comment by kimsojeong1225** [comment]
The following is the compute result of md5sum.
c762db294eb55d8a62bebce2b102e4f3 ./weak_val.hdf5
aa59c8c909d1dfe6184e768519875348 ./devtest.hdf5
21562439bcd9f248fcd82f671598b2e5 ./synth_val.hdf5
4744a84758e2194b7eaa1e7760f575bb ./synth_train.hdf5
2ad1728fb01ac2f1cdc8c71516c9f6fd ./unlabeled_train.hdf5
eed6eaf32932cb2002c2a4cc90d0641b ./weak_train.hdf5

weak_val.hdf5,devtest.hdf5,synth_train.hdf5 have some errors seems to have any errors.

**Comment by popcornell** [comment]
I re-downloaded synth_train.hdf5 from https://zenodo.org/record/6539466/files/ast_synth_train.tar.gz?download=1 and the MD5 checksum is fine for me. 

Is your internet connection stable ? You might have lost some packets when downloading the data and thus it got corrupted.

**Comment by kimsojeong1225** [comment]
Retry downloading and finally solved it! 
Thanks :)
