### ISSUE TITLE
Files don't get saved when downloading

### ISSUE THREAD

**Issue by niclas-b** [DCASE-REPO/DESED_task#64]
Hello,

using the `dcase2022_task4_baseline/generate_dcase_task4_2022.py` script downloading the audio data using the desed package is showing a progress bar with reasonable speed, but the files just don't get saved in the filesystem. I tried both using Windows 10 (and adjusting the filepaths) or opening the repo directory within a docker unix container and running it there.

However, when I use the original DESED repo and apply the same functions, the files get saved. What could be the reason for this?

Regards

**Comment by turpaultn** [comment]
Hi there, 

Could you give us the exact command you run with generate_dcase_task4_2022 please ? 
And same way with the orginal DESED repo. 

By the way, are we talking about the real or synthetic audio data or both ?

Best,

**Comment by turpaultn** [comment]
Ok, then we could add a little line saying that youtube-dlp should be up to date to use the repo (if you want to make a pull request, I'm fine by that)
