### ISSUE TITLE
Test step takes long time

### ISSUE THREAD

**Issue by niclas-b** [DCASE-REPO/DESED_task#70]
Hi,

the testing step in the 2022 recipe lasts much longer than the validation step, even though it uses the same amount of data and the on_test_epoch_end function has not been called yet. Is there something I don't see or what might be the reason for that?

Best regards

**Comment by florian-angulo** [comment]
Hi,

This year, metrics computation for the validation set and the test set include the threshold-independent PSDS from sed_scores_eval in addition to the legacy PSDS computation from the psds_eval package. This accounts for the additional computation time you noticed compared to previous years.

**Comment by florian-angulo** [comment]
Hi again,

I misread your question sorry. For the 2022 recipe (and the other ones as well) we only compute one operating point (threshold = 0.5) to monitor the intersection-based metric.

Then, in the test step, we use 50 operating points to get the PSDS curves from which we compute the scores (PSDS1 and PSDS2). This is why the test step is longer than the validation step.
