### ISSUE TITLE
AttributeError: 'Energy' object has no attribute 'kwh'

### ISSUE THREAD

**Issue by swagshaw** [DCASE-REPO/DESED_task#73]
https://github.com/DCASE-REPO/DESED_task/blob/a117c362f26f707492391362bb276927d8c7573f/recipes/dcase2023_task4_baseline/local/sed_trainer.py#L895

Here is a little typo. It should be `kWh` not `kwh`. 
It also exist in the func `on_test_end`.

**Comment by florian-angulo** [comment]
Hello @swagshaw,

You are right, we did not realize we had an older version of codecarbon when we ran our experiments with the new releases of the baseline.
I verified the checkpoints we provide to resume training or perform testing: they seem compatible with codecarbon 2.1.4.
We will fix this soon. 

Thanks for the input !
