### ISSUE TITLE
error: Couldn't find a setup script in /tmp/easy_install-zeojqoxu/scipy-1.11.2.tar.gz

### ISSUE THREAD

**Issue by karnapatel10** [DCASE-REPO/DESED_task#79]
getting this error on running setup command
python3 setup.py install

**Comment by turpaultn** [comment]
Hi, 
Can you please tell on which OS you are ? 
I suspect it is one of the dependencies, could you try installing each of them using pip to see which one is having a problem ?

**Comment by karnapatel10** [comment]
Ubuntu 22.04.2 LTS

**Comment by karnapatel10** [comment]
Thanks, the issue is resolved..
