### ISSUE TITLE
undefined symbol: _ZNK5torch8autograd4Node4nameEv 

### ISSUE THREAD

**Issue by karnapatel10** [DCASE-REPO/DESED_task#81]
OSError: /home/karna/miniconda3/envs/sedb/lib/python3.8/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv

Getting this error on running train_sed.py for DCASE 2022 baseline.

Earlier was getting No module named 'desed_task.dataio'
then included
            import sys
            sys.path.append('../../')
to include desed_task.dataio path.

but now getting above mentioned error, not able to figure out how to solve, kindly help

**Comment by turpaultn** [comment]
Hi there, 
You have a problem with your environment from what I see.
Did you install torchaudio using conda ? How did you install desed_task ?
Can you send a `conda list` of your environment, this could help.

**Comment by karnapatel10** [comment]
I created environment using the script provided, all the packages were installed successfully, I installed them individually again. 
Then I ran setup.py as mentioned in the repo, with python setup.py install. Everything was installed successfully.

conda list which I have got in my environment is as follows:


# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asteroid                  0.4.1                    pypi_0    pypi
asteroid-filterbanks      0.4.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
audioread                 3.0.0            py38h578d9bd_1    conda-forge
black                     19.10b0                  pypi_0    pypi
blas                      1.0                    openblas
bottleneck                1.3.5            py38h7deecbd_0
brotli-python             1.1.0            py38h17151c0_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.0               h5eee18b_0
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
cachetools                5.3.1                    pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.15.1           py38h74dc2b5_0
cfgv                      3.4.0                    pypi_0    pypi
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cudatoolkit               11.3.1               h2bc3f7f_2
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dcase-util                0.2.16                   pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
desed                     1.3.6                    pypi_0    pypi
desed-task                0.1.0                    pypi_0    pypi
distlib                   0.3.7                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
exceptiongroup            1.1.3                    pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0
filelock                  3.12.3                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.9.0                 pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2            py38heeb90bb_0
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.22.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.57.0                   pypi_0    pypi
h5py                      3.9.0            py38he06866b_0
hdf5                      1.12.1               h70be1eb_2
identify                  2.5.27                   pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0            py38h06a4308_0
importlib-resources       6.0.1                    pypi_0    pypi
importlib_metadata        6.0.0                hd3eb1b0_0
iniconfig                 2.0.0                    pypi_0    pypi
jams                      0.3.4                    pypi_0    pypi
jinja2                    3.1.2            py38h06a4308_0
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
jsonschema                4.19.0                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
kiwisolver                1.4.5            py38h7f3f72f_0    conda-forge
krb5                      1.20.1               h568e23c_1
lame                      3.100             h166bdaf_1003    conda-forge
lazy-dataset              0.0.14                   pypi_0    pypi
lazy_loader               0.3                pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   8.2.1                h91b91d3_0
libdeflate                1.17                 h5eee18b_0
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h7f8727e_1
libffi                    3.3                  he6710b0_2
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm14                 14.0.6               hef93074_0
libnghttp2                1.52.0               ha637b67_1
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.21               h043d6bf_0
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h5eee18b_0
libprotobuf               3.20.3               he621ea3_0
librosa                   0.10.1             pyhd8ed1ab_0    conda-forge
libsndfile                1.2.2                hbc2eb40_0    conda-forge
libssh2                   1.10.0               h37d81fd_2
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.1                h6a678d5_0
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.7.0                h439df22_0
libwebp                   1.2.4                h1daa5a0_1    conda-forge
libwebp-base              1.2.4                h5eee18b_1
libzlib                   1.2.13               hd590300_5    conda-forge
lightning-utilities       0.9.0                    pypi_0    pypi
llvm-openmp               14.0.6               h9e868ea_0
llvmlite                  0.40.0           py38he621ea3_0
lz4-c                     1.9.4                hcb278e6_0    conda-forge
mad                       0.15.1b              h9c3ff4c_1    conda-forge
markdown                  3.4.4                    pypi_0    pypi
markupsafe                2.1.1            py38h7f8727e_0
matplotlib-base           3.4.3            py38hf4fb855_1    conda-forge
mir-eval                  0.7                      pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mpg123                    1.31.3               hcb278e6_0    conda-forge
mpmath                    1.3.0            py38h06a4308_0
msgpack-python            1.0.5            py38hfbd4bf9_0    conda-forge
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  3.1              py38h06a4308_0
ninja                     1.10.2               h06a4308_5
ninja-base                1.10.2               hd09550d_5
nodeenv                   1.8.0                    pypi_0    pypi
numba                     0.57.1           py38hd559b08_0    conda-forge
numexpr                   2.8.4            py38hd2a5715_1
numpy                     1.24.3           py38hf838250_0
numpy-base                1.24.3           py38h1e6e340_0
oauthlib                  3.2.2                    pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1v               hd590300_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3            py38h417a72b_0
pathlib                   1.0.1                    pypi_0    pypi
pathspec                  0.11.2                   pypi_0    pypi
pb-bss-eval               0.0.2                    pypi_0    pypi
pesq                      0.0.4                    pypi_0    pypi
pillow                    9.4.0            py38h6a678d5_0
pip                       23.2.1           py38h06a4308_0
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0                    pypi_0    pypi
pooch                     1.7.0              pyha770c72_3    conda-forge
pre-commit                3.4.0                    pypi_0    pypi
protobuf                  4.24.2                   pypi_0    pypi
psds-eval                 0.5.3                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycodestyle               2.5.0                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydeprecate               0.3.1                    pypi_0    pypi
pydot-ng                  2.0.0                    pypi_0    pypi
pyloudnorm                0.1.1                    pypi_0    pypi
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pysoundfile               0.12.1             pyhd8ed1ab_0    conda-forge
pystoi                    0.3.3                    pypi_0    pypi
pytest                    7.4.1                    pypi_0    pypi
python                    3.8.5                h7579374_1
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-magic              0.4.27                   pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   2.0.1           cpu_py38hab5cca8_0
pytorch-lightning         1.5.1                    pypi_0    pypi
pytorch-mutex             1.0                         cpu    pytorch
pytorch-ranger            0.1.1                    pypi_0    pypi
pytz                      2022.7           py38h06a4308_0
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
referencing               0.30.2                   pypi_0    pypi
regex                     2023.8.8                 pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
rpds-py                   0.10.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scaper                    1.6.5                    pypi_0    pypi
scikit-learn              1.3.0            py38hc099248_0    conda-forge
scipy                     1.10.1           py38h32ae08f_1
sed-eval                  0.2.1                    pypi_0    pypi
sed-scores-eval           0.0.0                    pypi_0    pypi
setuptools                68.0.0           py38h06a4308_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0                    pypi_0    pypi
sox                       1.4.0                    pypi_0    pypi
soxbindings               1.2.3                    pypi_0    pypi
soxr                      0.1.3                h0b41bf4_3    conda-forge
soxr-python               0.3.5            py38h31356c5_0    conda-forge
sqlite                    3.41.2               h5eee18b_0
sympy                     1.11.1           py38h06a4308_0
tbb                       2021.8.0             hdb19cb5_0
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.1                    pypi_0    pypi
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tk                        8.6.12               h1ccaba5_0
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch-optimizer           0.3.0                    pypi_0    pypi
torch-stoi                0.1.2                    pypi_0    pypi
torchaudio                2.0.2                  py38_cpu    pytorch
torchmetrics              0.7.3                    pypi_0    pypi
torchvision               0.15.2                 py38_cpu    pytorch
tornado                   6.3.3            py38h01eb140_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.5                    pypi_0    pypi
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
urllib3                   1.26.16                  pypi_0    pypi
validators                0.22.0                   pypi_0    pypi
virtualenv                20.24.4                  pypi_0    pypi
werkzeug                  2.3.7                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0
x264                      1!157.20191217       h7b6447c_0
xz                        5.4.2                h5eee18b_0
yarl                      1.9.2                    pypi_0    pypi
youtube-dl                2021.12.17         pyhd8ed1ab_0    conda-forge
zipp                      3.11.0           py38h06a4308_0
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hc292b87_0

**Comment by karnapatel10** [comment]
@turpaultn , I have sent my conda list. Can I get a reference conda a=list which i can use to compare with my conda list, as I am not able to get my issue resolved.

**Comment by karnapatel10** [comment]
Thanks for the response, the issue was due to non compatible versions of pytorch and torchaudio. One can refer to link [https://pytorch.org/audio/stable/installation.html](url) for supported versions.
