### ISSUE TITLE
Where is the downloaded dataset?

### ISSUE THREAD

**Issue by SevenKkkkkkk** [DCASE-REPO/DESED_task#95]
I have completely run the script: python generated_case_task4_2024. py, but in the directory DESED_task master/data/dcase/dataset/audio/train/, the strong_label_real, unlabel_in_domain, and weak are all empty.

When I run the script: Python train_pretrained.py, the result is as follows:
Resampling syntax folder to 16 kHz
Resampling synth_val_folder to 16 kHz
Resampling real_masestro_train_folder to 16 kHz
Resampling real_masestro_val_folder to 16 kHz
Resampling strong_folder to 16 kHz
0it [00:00,? It/s]
Resampling weak_folder to 16 kHz
0it [00:00,? It/s]
Resampling unlabeled_folder to 16 kHz
0it [00:00,? It/s]
Resampling test_folder to 16 kHz
0it [00:00,? It/s]
Global seed set to 42
Traceback (most recent call last):
File "/home/dl/data/DESED_task master/recipes/dcase2024_task4_baseline/train_pretrained. py", line 621, in<module>
Single_run（
File "/home/dl/data/DESED_task master/recipes/dcase2024_task4_baseline/train_pretrained. py", line 413, in single_run
Samplers=[torch. utils. data. RandomSampler (x) for x in tottrain_data]
File "/home/dl/data/DESED_task master/recipes/dcase2024_task4_baseline/train_pretrained. py", line 413, in<listcomp>
Samplers=[torch. utils. data. RandomSampler (x) for x in tottrain_data]
File "/home/dl/anaconda3/envs/dcase2024/lib/python3.8/site packages/torch/utils/data/sampler. py", line 143, in __ init__
Raise Value Error (f "num samples should be a positive integer value, but got num samples={self. num samples}")
Value Error: num samples should be a positive integer value, but got num samples=0

I don't know what to do, do I still need to add: only strong only real only synth only maestro after Python generated_case_task4_2024. py and run it again? Or should I do something else to solve this problem?

**Comment by SevenKkkkkkk** [comment]
![1](https://github.com/DCASE-REPO/DESED_task/assets/115334799/9828f817-bbac-4084-a75c-f9d86a0617f2)

**Comment by popcornell** [comment]
Hi Kai,

did you also generated the embeddings ?

**Comment by SevenKkkkkkk** [comment]
Hello,
Do you mean to run this script: Python extraction_embeddings. py -- output_dir/ Embeddings“
![2](https://github.com/DCASE-REPO/DESED_task/assets/115334799/ba8cafa1-f7ab-435a-9ec2-1125f58813d1)

I ran this script after running Python generated_case_task4_2024. py

However, I am currently running Python generated_case_task4_2024. py -- only strong/only real/only syntax/only maestro. I don't know if this will be effective.

After running Python generated_case_task4_2024. py -- only strong, the following prompt is given:
The file..// Data/dcase/dataset/metadata/train/audioset_strong. tsv already exists
Time of the program: 0.001397848129272461 s said that there is already a tsv file (where to download the corresponding wav file QAQ)

Just finished running Python generated_case_task4_2024. py -- only real gave the following prompt:
Please check your missing files: missing files, you can relaunch 'download.audiosed_sets' to try to include them, then, send them missing files to
Time of the program: 86329.15910863876 seconds
The dcase dataset has been saved in the following path:..// Data/dcase/dataset
Generatedcase_task4_2024. py:217: UserWarning: You have missing files
Please try to redownload dded_real again:
Import Desed
Desed. download_studioset_data ('../../data/dcase/dataset ', n_jobs=3, chunk_size=10)
Please send your missing files to the task organizers to get your missing files

![4](https://github.com/DCASE-REPO/DESED_task/assets/115334799/94f5e6a1-c8eb-440a-a338-c1efc1d7681c)

**Comment by popcornell** [comment]
Your download is successful you have to contact romain serizel via the link in website. 
Please follow the instructions there

**Comment by SevenKkkkkkk** [comment]
好的，我以为在这联系您也可以
![29678DC7](https://github.com/DCASE-REPO/DESED_task/assets/115334799/6926efd4-7c41-45a4-a986-f612f2640df0)
，谢谢您的耐心回复！祝好！
