### ISSUE TITLE
question about the label mapping

### ISSUE THREAD

**Issue by apple-yinhan** [DCASE-REPO/DESED_task#97]
Hi there, I see that we have a label mapping dict here.
But in the groundtruth of MAESTRO, I think we only have "people talking", not "people_talking".
It seems that there is an additional underscore for the event "people talking" in this mapping dict.
![图片1](https://github.com/DCASE-REPO/DESED_task/assets/115258619/0d08d07b-8c72-4081-ab51-63d7500e43cc)
![图片2](https://github.com/DCASE-REPO/DESED_task/assets/115258619/f98d14c4-ee90-46e8-a3a3-3758fd57b760)

**Comment by popcornell** [comment]
Sorry, thanks for reporting. 
I think I got confused because sometimes there are underscored sometimes not. 
I fixed it and I am rerunning the baseline.

**Comment by apple-yinhan** [comment]
Thank you. Wish to see your result.

**Comment by popcornell** [comment]
The impact was quite minimal. 
But there was another issue where one of the datasets did not have the mask argument. 
That was more significant regarding MAESTRO performance

**Comment by apple-yinhan** [comment]
Thanks!
